# Generated by Django 5.2.8 on 2025-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_uploadbatch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='low_confidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
